### ISSUE TITLE
punctuation mark

### ISSUE THREAD

**Issue by georgejean** [jesusalber1/google-translate-cli#6]
Hi,

Is there a way to take account of some punctuation marks like "." and "?" and get full translated text (comma seems to be supported).
Example (we don't get full translated text):
Input:
`translate -s en -t fr 'Hello, my name is Gérard. How are you? Great, thank you'`
Output:
`'Bonjour, je m'appelle Gérard.'`
(expected: `'Bonjour, je m'appelle Gérard. Comment allez-vous? Bien, merci'`)

**Comment by georgejean** [comment]
I don't code in javascript so I don't understand the translate.js file.
But the `(\d.)+` in the regexp (line `var values = body.match((/"([^"]+)"|(\d.)+/g));`)
seems strange to me and I would like to understand the aim of this line (perhaps, the problem comes from there?).

EDIT:
I understand the code much better now.
The useful data of body is stored in the `values` array, even if there are several sentences.
Example with:
`translate -s en -t fr "What time is it? It's half past twelve"`
Here `body` is
```javascript
[[["Quelle heure est-il? ","What time is it?",,,1],["Il est midi et demi","It's half past twelve",,,1]],,"en"]
```
and `values` is
```javascript
[ '"Quelle heure est-il? "',
  '"What time is it?"',
  '1]',
  '"Il est midi et demi"',
  '"It\'s half past twelve"',
  '1]',
  '"en"' ]
```
(useful data are here in `values[0]` and `values[3]`)
We could get the first subarray in body to build all the sentences. It would be better not to use such things as
`eval()` or `new Function` but a good regexp instead (`\[\[".*?\]\]` should do the trick).
I will think about it and suggest something when I'll have more time.

**Comment by georgejean** [comment]
I think that #7 solves the problem.

**Comment by jesusalber1** [comment]
You're right! Just checked it out! I was working with a previous version when I wrote the last message. Great! 😃
